site_name:        SwiftXcode
site_url:         https://SwiftXcode.github.io/
site_author:      ZeeZide GmbH
copyright:        Â© ZeeZide GmbH 2018
repo_url:         https://github.com/SwiftXcode/swift-xcode
google_analytics: [ 'UA-3266252-11', 'mod-swift.org' ]
  
docs_dir:    content
site_dir:    docs

theme:       readthedocs
theme_dir:   custom_theme
extra_css:   [ extra.css ]

pages:
  - 'Introduction':            'index.md'
  - 'Installation':            'install.md'
  - 'Usage':                   'usage.md'
  - 'Images':                  'images.md'
  - 'Goals':                   'goals.md'
  - 'About':                   'about.md'
